name: castboard_fonts
description: Provides inbuilt fonts for the Castboard software suite.
version: 0.0.1
homepage: www.castboard.app

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_lints: ^1.0.0
  path: ^1.8.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
fonts:
  - family: Abril Fatface
    fonts:
      - asset: AbrilFatface-Regular.ttf
  - family: Alfa Slab One
    fonts:
      - asset: AlfaSlabOne-Regular.ttf
  - family: Arima Madurai
    fonts:
      - asset: ArimaMadurai-Black.ttf
      - asset: ArimaMadurai-Bold.ttf
      - asset: ArimaMadurai-ExtraBold.ttf
      - asset: ArimaMadurai-ExtraLight.ttf
      - asset: ArimaMadurai-Light.ttf
      - asset: ArimaMadurai-Medium.ttf
      - asset: ArimaMadurai-Regular.ttf
      - asset: ArimaMadurai-Thin.ttf
  - family: Arvo
    fonts:
      - asset: Arvo-Bold.ttf
      - asset: Arvo-BoldItalic.ttf
      - asset: Arvo-Italic.ttf
      - asset: Arvo-Regular.ttf
  - family: Averia Serif Libre
    fonts:
      - asset: AveriaSerifLibre-Bold.ttf
      - asset: AveriaSerifLibre-BoldItalic.ttf
      - asset: AveriaSerifLibre-Italic.ttf
      - asset: AveriaSerifLibre-Light.ttf
      - asset: AveriaSerifLibre-LightItalic.ttf
      - asset: AveriaSerifLibre-Regular.ttf
  - family: Bebas Neue
    fonts:
      - asset: BebasNeue-Regular.ttf
  - family: Cardo
    fonts:
      - asset: Cardo-Bold.ttf
      - asset: Cardo-Italic.ttf
      - asset: Cardo-Regular.ttf
  - family: Chonburi
    fonts:
      - asset: Chonburi-Regular.ttf
  - family: Cinzel
    fonts:
      - asset: Cinzel-VariableFont_wght.ttf
      - asset: README.txt
  - family: Comfortaa
    fonts:
      - asset: Comfortaa-VariableFont_wght.ttf
      - asset: README.txt
  - family: Concert One
    fonts:
      - asset: ConcertOne-Regular.ttf
  - family: Cormorant Garamond
    fonts:
      - asset: CormorantGaramond-Bold.ttf
      - asset: CormorantGaramond-BoldItalic.ttf
      - asset: CormorantGaramond-Italic.ttf
      - asset: CormorantGaramond-Light.ttf
      - asset: CormorantGaramond-LightItalic.ttf
      - asset: CormorantGaramond-Medium.ttf
      - asset: CormorantGaramond-MediumItalic.ttf
      - asset: CormorantGaramond-Regular.ttf
      - asset: CormorantGaramond-SemiBold.ttf
      - asset: CormorantGaramond-SemiBoldItalic.ttf
  - family: EB Garamond
    fonts:
      - asset: EBGaramond-Italic-VariableFont_wght.ttf
      - asset: EBGaramond-VariableFont_wght.ttf
      - asset: README.txt
  - family: Fredoka One
    fonts:
      - asset: FredokaOne-Regular.ttf
  - family: Gravitas One
    fonts:
      - asset: GravitasOne-Regular.ttf
  - family: Libre Baskerville
    fonts:
      - asset: LibreBaskerville-Bold.ttf
      - asset: LibreBaskerville-Italic.ttf
      - asset: LibreBaskerville-Regular.ttf
  - family: Limelight
    fonts:
      - asset: Limelight-Regular.ttf
  - family: Lobster
    fonts:
      - asset: Lobster-Regular.ttf
  - family: Lobster Two
    fonts:
      - asset: LobsterTwo-Bold.ttf
      - asset: LobsterTwo-BoldItalic.ttf
      - asset: LobsterTwo-Italic.ttf
      - asset: LobsterTwo-Regular.ttf
  - family: Lora
    fonts:
      - asset: Lora-Italic-VariableFont_wght.ttf
      - asset: Lora-VariableFont_wght.ttf
      - asset: README.txt
  - family: Merriweather
    fonts:
      - asset: Merriweather-Black.ttf
      - asset: Merriweather-BlackItalic.ttf
      - asset: Merriweather-Bold.ttf
      - asset: Merriweather-BoldItalic.ttf
      - asset: Merriweather-Italic.ttf
      - asset: Merriweather-Light.ttf
      - asset: Merriweather-LightItalic.ttf
      - asset: Merriweather-Regular.ttf
  - family: Passion One
    fonts:
      - asset: PassionOne-Black.ttf
      - asset: PassionOne-Bold.ttf
      - asset: PassionOne-Regular.ttf
  - family: Patua One
    fonts:
      - asset: PatuaOne-Regular.ttf
  - family: Playfair Display
    fonts:
      - asset: PlayfairDisplay-Italic-VariableFont_wght.ttf
      - asset: PlayfairDisplay-VariableFont_wght.ttf
      - asset: README.txt
  - family: PT Serif
    fonts:
      - asset: PTSerif-Bold.ttf
      - asset: PTSerif-BoldItalic.ttf
      - asset: PTSerif-Italic.ttf
      - asset: PTSerif-Regular.ttf
  - family: Righteous
    fonts:
      - asset: Righteous-Regular.ttf
  - family: Special Elite
    fonts:
      - asset: LICENSE.txt
      - asset: SpecialElite-Regular.ttf
  - family: Staatliches
    fonts:
      - asset: Staatliches-Regular.ttf
  - family: Tinos
    fonts:
      - asset: LICENSE.txt
      - asset: Tinos-Bold.ttf
      - asset: Tinos-BoldItalic.ttf
      - asset: Tinos-Italic.ttf
      - asset: Tinos-Regular.ttf
  - family: Vollkorn
    fonts:
      - asset: README.txt
      - asset: Vollkorn-Italic-VariableFont_wght.ttf
      - asset: Vollkorn-VariableFont_wght.ttf
